# Generated by Django 2.2.6 on 2019-11-07 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anniversary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadet',
            options={'verbose_name': 'cadete', 'verbose_name_plural': 'cadetes'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'promoción', 'verbose_name_plural': 'promociones'},
        ),
    ]
